name: Deploy Images to Firebase

on:
  push:
    branches:
      - main
    # Only run if files in the 'Public' folder change
    paths:
      - 'Public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TMPAPP }}'
          channelId: live
          projectId: tmp-app-site
